config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

resources :tasks

  get 'home' => 'tasks#home'

  get 'accueil'=>'tasks#accueil'

  get 'concept'=>'tasks#concept'

  get 'activités'=>'tasks#activite'

  get "livredor" => "tasks#index"

  get "livredornew" => "tasks#new"

  get "impressum" =>"tasks#impressum"




   root to: 'tasks#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

validates :name, presence: { message:"Merci de compléter votre prénom"}
validates :child_name, presence: { message:"Merci de compléter le prénom de l'enfant"}
validates :promotion, presence: { message:"Merci de compléter l'année"}

after_save :send_nvmsg_email

private

def send_nvmsg_email
  UserMailer.nvmsg.deliver_now
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show

    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

   def create
    @task = Task.new(task_params)
    if @task.save
       redirect_to tasks_url
        flash[:notice] ="Votre message a été envoyé avec succès. Il apparaîtra sur le site dans quelques jours"

    else
      render :new
    end

  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to :action => 'index'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

    def task_params
      params.require(:task).permit(:name, :child_name, :promotion, :description, :statut)
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_banner.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li><%= image_tag("logo modifié meme propo2.png", width: '100%', alt: 'Krabbelstuff logo',)%></li>
            <li> <%= image_tag("texte_creche.png", width: '50%', alt: 'texte creche',) %></li>
             <li>No d'agrément: MR467/6</li>
          </ul>
        </div>

        <div id="banner-right" >
          <ul>
            <li><%= image_tag("photo-karbbelstuff.png", alt: '"Krabbelstuff photo',) %></li>
          </ul>
        </div>
        <div class="banner-down-center">
            CRECHE AGREE ET CONVENTIONNEE PAR LE MINISTERE DE L’EDUCATION NATIONALE ET LA COMMUNE D'ESCH-SUR-SÜRE
        </div>
      </div>
    </div>

app/views/layouts/_banner1_home.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li><%= image_tag("logo3.png", alt: 'Krabbelstuff logo',)%></li>
          </ul>
        </div>
        <div id="banner-right-fixe" >
          <ul>
            <li><%= image_tag("photo-karbbelstuff.png", alt: '"Krabbelstuff photo',) %></li>
          </ul>
        </div>
      </div>
      <div class="banner-down-center">
     <p>CR&#200;CHE ASBL D’INSPIRATION MONTESSORI</p><p> AGR&#201;&#201;E ET CONVENTIONN&#201;E PAR LE MINIST&#200;RE DE L’&#201;DUCATION NATIONALE ET LA COMMUNE D'ESCH-SUR-S&Ucirc;RE</p>
      </div>
    </div>

app/views/layouts/_banner2.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li>
              <%= image_tag("logo modifié meme propo2.png", width: '100%', alt: 'Krabbelstuff logo',) %> </li>
            <li> <%= image_tag("texte_creche.png", width: '50%', alt: 'texte creche',) %></li>
             <li>No d'agrément: MR467/6</li>
          </ul>
        </div>
        <div id="banner-right" >
          <div class="image-carousel">
            <div class="inner">
              <%= image_tag("photo_groupe1.jpg", alt: '1',) %>
              <%= image_tag("photo_groupe2.jpg", alt: '2',) %>
              <%= image_tag("photo_groupe3.jpg", alt: '3',) %>
              <%= image_tag("photo_groupe4.jpg", alt: '4',) %>
              </div>
            <div class="bubbles"></div>
            <div class="prev"></div>
            <div class="next"></div>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_banner2_accueil.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li class="bébé"><%= image_tag("logo3.png", alt: 'Krabbelstuff logo')%></li>

          </ul>
        </div>
        <div id="banner-right" >
          <div class="carousel-data">
            <ul>
              <li><%= image_tag("acc1.jpg", alt: '1') %></li>
              <li><%= image_tag("acc2.jpg", alt: '1') %></li>
              <li><%= image_tag("acc3.jpg", alt: '1') %></li>
              <li><%= image_tag("acc4.jpg", alt: '1') %></li>
              <li><%= image_tag("acc5.jpg", alt: '1') %></li>
              <li><%= image_tag("acc6.jpg", alt: '1') %></li>
              <li><%= image_tag("acc7.jpg", alt: '1') %></li>
            </ul>
          </div>

          <div class="carousel-wrapper">
            <div class="carousel-image-title">
              <div class="carousel-image"><img src="" alt="" />
              </div>
            </div>
            <div class="carousel-nav"></div>
          </div>
        </div>
      </div>

app/views/layouts/_banner3.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li><%= image_tag("logo modifié meme propo2.png", width: '100%', alt: 'Krabbelstuff logo',)%></li>
            <li> <%= image_tag("texte_creche.png", width: '50%', alt: 'texte creche',) %></li>
          <li>No d'agrément: MR467/6</li>
          </ul>
        </div>

        <div id="banner-right" >
          <ul>
            <li><%= image_tag("photo-karbbelstuff.png", alt: '"Krabbelstuff photo',) %></li>
          </ul>
        </div>
      </div>
    </div>

app/views/layouts/_banner3_concept.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li class="bébé"><%= image_tag("logo3.png", alt: 'Krabbelstuff logo',)%></li>

          </ul>
        </div>
        <div id="banner-right" >
          <div class="carousel-data">
            <ul>
              <li><%= image_tag("conc3.jpg", alt: '1') %></li>
              <li><%= image_tag("conc4.jpg", alt: '1') %></li>
              <li><%= image_tag("conc5.jpg", alt: '1') %></li>
              <li><%= image_tag("conc6.jpg", alt: '1') %></li>
              <li><%= image_tag("conc7.jpg", alt: '1') %></li>
              <li><%= image_tag("conc8.jpg", alt: '1') %></li>
              <li><%= image_tag("conc10.jpg", alt: '1') %></li>
             </ul>
          </div>

          <div class="carousel-wrapper">
            <div class="carousel-image-title">
              <div class="carousel-image"><img src="" alt="" />
              </div>
            </div>
            <div class="carousel-nav"></div>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_banner4_activite.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li class="bébé"><%= image_tag("logo3.png", alt: 'Krabbelstuff logo',)%></li>

          </ul>
        </div>
        <div id="banner-right" >
          <div class="carousel-data">
            <ul>
              <li><%= image_tag("conc13.jpg", alt: '1') %></li>
              <li><%= image_tag("act12.jpg", alt: '1') %></li>
              <li><%= image_tag("acc11.jpg", alt: '1') %></li>
              <li><%= image_tag("acc12.jpg", alt: '1') %></li>
              <li><%= image_tag("acc10.jpg", alt: '1') %></li>
              <li><%= image_tag("conc11.jpg", alt: '1') %></li>
              <li><%= image_tag("conc12.jpg", alt: '1') %></li>
            </ul>
          </div>

          <div class="carousel-wrapper">
            <div class="carousel-image-title">
              <div class="carousel-image"><img src="" alt="" />
              </div>
            </div>
            <div class="carousel-nav"></div>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/_banner5_livredor.html.erb
<div id="content">
  <div class="container-fluid">
    <div class="banner-description">
      <div id="banner-distributed">
        <div id="banner-left">
          <ul>
            <li><%= image_tag("logo3.png", alt: 'Krabbelstuff logo',)%></li>

          </ul>
        </div>

        <div id="banner-right-fixe" >
          <ul>
            <li><%= image_tag("photo-karbbelstuff.png", alt: '"Krabbelstuff photo',) %></li>
          </ul>
        </div>

        <div class="banner-down-center">

        </div>
      </div>
    </div>

app/views/layouts/_footer.html.erb
<div class="footer-description">
  <div id="footer-distributed">
    <div id="footer-left">
      <ul>
        <li><u>Nous contacter : </u></li>
        <li>Crèche Krabbelstuff</li>
        <li>4 an der Gaass</li>
        <li>L-9157 Heiderscheid</li>
        <li>Tél : +352 26 88 90 28</li>
        <li>Mail : krabbels@pt.lu</li>
                <li><p>

                </p></li>
        <li> <u><a href="impressum">Impressum</a></u></li>
      </ul>
    </div>
    <div id="footer-right" >
      <ul>
        <li></li>
        <li><u>Heures d’ouverture :</u></li>
        <li> 7 :00-18 :15 et selon les besoins sur demande</li>
        <li> du lundi au vendredi </li>

        <li>Jours de fermeture communiqués à l’avance par la crèche</li>
        <li></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Krabbelstuff</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
  </head>
  <body>



    <%= yield %>

      <%= render "layouts/footer" %>

    </div>
</div>

      <%= javascript_include_tag 'application' %>
      <script src="javascripts/image-carousel.js"></script>
      <script type="text/scss" src="stylesheets/carrousel.scss"></script>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

app/views/tasks/accueil.html.erb
     <%= render "layouts/banner2_accueil" %>

      <div class="card-description">
        <ul class="barre barre-pills barre-justified">
          <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
          <li class='active'><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
          <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
          <li ><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
          <li ><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>

        </ul>
      </div>
      <div class="card-description text-center">
        <h3 class="citation"> <strong><i> "Le véritable enseignement n’est point de te parler mais de te conduire"</i></strong></h3>
                    <h3>- Antoine de Saint-Exupéry</h3>
      </div>


      <div class="card-description">
            <!-- <div class="changement"><i><strong>Notre but est de « forger et cultiver le plaisir d’apprendre, de découvrir et d’agir ».</strong></i></div>
            <div class="texte_centre">Les petits enfants seront accueillis dans notre maison sans discrimination philosophique, religieuse ou raciale.</div> -->
           <h2><strong><u>Notre mission</u></strong></h2>
                <ul>
                  <li>permettre à chaque enfant à avoir confiance en sa capacité d’apprendre et l'aider à stimuler sa participation dans le groupe selon ses capacités liées à son âge ;</li>
                  <li>développer des activités éducatives, pédagogiques, sociales et culturelles selon une charte qualité ;</li>
                  <li>travail de prévention pour la petite enfance.</li>
                </ul>
              <p>Notre maison <u>prépare à la vie et à la scolarisation</u>. Elle aide les enfants à grandir et à se développer en étant riches de leurs différences. Notre maison accueillera chaque enfant tel qu’il est avec ses capacités et ses faiblesses, sans préjugés. Les petits enfants seront accueillis dans notre maison sans discrimination philosophique, religieuse ou raciale.</p>

              <P>Nous sommes <u>un « relais »,</u> un milieu d’accompagnement des petits enfants en partenariat avec les parents, en les impliquant et en les soutenant par notre motivation dans leurs démarches. Ils trouvent chez nous écoute et soutien. Nous organisons des échanges journaliers.</p>

              <p>Notre volonté est de protéger <u>l’environnement.</u> Nos aliments proviennent d’une firme qui privilégie les produits Luxembourgeois et issus du commerce équitable. Nos langes et lingettes sont bio hypoallergéniques. Les boissons proviennent du commerce local et uniquement en bouteilles en verre. : « Boissons Wallers ». Pas d’eau du robinet !</p>

              <p>Nos règles d’hygiène sont très strictes : désinfection et lavage des draps journaliers.</p>


      </div>

app/views/tasks/activite.html.erb
 <%= render "layouts/banner4_activite" %>

<div class="card-description">
  <ul class="barre barre-pills barre-justified">
    <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
    <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
    <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
    <li class='active'><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
    <li ><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>

  </ul>
</div>
<div class="card-description">
  <div class="card-distributed">
    <h2><strong><u>Nos activités :</u></strong></h2>
     <div class="card-activite-down">
      <ul>
        <li> Activités d’expression corporelle et d’expression orales (apprentissage du Multilinguisme) :
          <p>De fait, la communication est extrêmement importante, comme en témoigne la citation de Françoise Dolto : </p>
          <p><i>« Il faut parler aux enfants. Il faut parler aux enfants dès qu’ils naissent. Il faut leur parler comme à des adultes, il ne faut pas leur parler bébé.</i></p>
          <p><i>Il faut leur parler un langage articulé, il faut s’adresser à eux en partant de l’idée qu’ils nous comprennent et qu’ils vont faire quelque chose de ce qu’on leur dit.»</i></p></li>
        <li>Le jeu libre occupe une place primordiale pour le développement de l’enfant.</li>
        <li>Activités pour le développement sensoriel et créatif
          <ul>
            <li> Comme le bricolage, pâte à modeler : toucher, créer et regarder</li>
            <li> Comme la musique : éveil musical promouvoir l’esprit d’équipe et la créativité</li>
            <li> Comme la peinture et le dessin : promouvoir la créativité et l’expression des émotions</li>
            <li> Activités pour le développement moteur comme baby-gym, animer des marionnettes…</li>
            <li> Comme cuisiner, sentir les ingrédients, goûter et toucher les préparations</li>
          </ul>
        </li>
        <li> Activités extérieures comme les promenades, jeux en plein air…</li>
        </ul>
    </div>
  </div>
</div>

app/views/tasks/concept.html.erb
 <%= render "layouts/banner3_concept" %>

<div class="card-description">
  <ul class="barre barre-pills barre-justified">
     <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
          <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
          <li class='active'><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
          <li ><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
          <li ><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>
  </ul>
</div>
<div class="card-description text-center">
  <h3 class="citation"> <strong><i> "Il faut aimer l'enfant pour ce qu'il est et non pour ce qu'on veut qu'il soit."</i></strong></h3>
  <h3>- Janusz Korczack</h3>
</div>


<div class="card-description">
  <div class="card-distributed">
  <h2><strong><u>Nos objectifs</u></strong></h2>
    <div class="card-left">
      <ul>
        <h5>Les 0 - 1 an : « le cocooning »</h5>
        <li>Favoriser les interactions avec l’entourage, </li>
        <li>Apporter la sécurité du cocon familial aux petits enfants,</li>
        <li>Privilégier leurs rythmes, </li>
        <li>Adoucir les séparations avec leurs mamans et les rassurer.</li>
      </ul>
    </div>
    <div class="card-center">
      <ul>
        <h5>Les 1 - 2 ans : « l’éveil »</h5>
        <li>Susciter leur intérêt via des ateliers :
        (Gym douce, comptines, cache-cache, éveil musical),</li>
        <li>Aide à l’acquisition de la marche,</li>
        <li>Aide à l’acquisition de la parole : Initiation au Luxembourgeois et au Français,</li>
        <li>Aide pour manger seul et avec des couverts,</li>
        <li>Découverte de l’environnement et éveil à la collectivité,</li>
        <li>Apprentissage du jeu seul et en groupe,</li>
        <li>Aide à accepter les interdits,</li>
        <li>Aide pour sortir de «l’égocentrisme du tout petit».</li>
      </ul>
    </div>
    <div class="card-right">
      <ul>
          <h5>Les 2 - 4   ans : « l’apprentissage par le jeu »</h5>
          <li>Acquisition de l’autonomie et de la propreté,</li>
          <li>Perfectionnement de la marche,</li>
          <li>Perfectionnement du langage : jeux de mots etc…,</li>
          <li>Communication avec l’enfant et l’apaiser dans sa crise d’opposition,</li>
          <li>Développer son côté artistique et son habilité manuelle, </li>
          <li>Favoriser les découvertes via les ateliers de jeux,</li>
          <li>Valoriser le petit enfant dans ses activités pour avoir confiance en soi,</li>
          <li>Développer son imaginaire,</li>
          <li>Apprentissage à s’habiller et se déshabiller seul,</li>
          <li>Séance de psychomotricité : gym et natation chaque semaine.</li>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
 <%= render "layouts/banner5_livredor" %>


  <div class="card-description">
    <ul class="barre barre-pills barre-justified">
     <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
     <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
     <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
     <li><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
     <li class='active'><<a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>
   </ul>
 </div>
  <div class="card-description">
    <div class="card-distributed">
      <div class="card-ldo first">
        <div class="card-ldo-left">
          <table>
            <tr>
            <%= form_for @task do |f| %>

              <td> Nom des Parents: </td>
              <td> <%= f.text_field :name %></td>
            </tr>

            <tr>
              <td>Prénom de l'Enfant: </td>
              <td><%= f.text_field :child_name %></td>
            </tr>

            <td>Année: </td>
              <td><%= f.text_field :promotion %></td>
            </tr>
            </table>
          </div>
          <div class="card-ldo-right">
            <p> Votre message : </p>
            <%= f.text_area :description %>
          </div>

          <div class="card-ldo-down">
            <%= f.submit value="mise à jour"%>
            <%= link_to "cancel", tasks_path %>
            <% end %>
          </div>
      </div>
    </div>
  </div>

app/views/tasks/home.html.erb
   <%= render "layouts/banner1_home" %>

<div class="card-description">
  <ul class="barre barre-pills barre-justified">
    <li class='active'><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
    <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
    <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
    <li ><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
    <li ><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>
  </ul>
</div>
<div class="card-description">
  <div class="card-distributed">
  <h2><strong><u>Nos atouts</u></strong></h2>
    <div class="home-card-left">
     <ul>
      <h5>Petite crèche familiale pour enfants de 0-4 ans</h5>
      <li class="image"> <%= image_tag("cheques_services.png", width: '300', height: '150', alt: 'cheque service',) %>
      </li>
      <li>Nous facturons uniquement suivant les chèques services</li>
      <li>Pas de dépassement des tarifs chèques service</li>
      <li>Plus de 10 ans d'expérience en tant que crèche avec du personnel formé à l'encadrement de la petite enfance</li>
    </ul>
  </div>
<div class="home-card-right">
      <ul>
      <h5>Nos avantages</h5>
        <li> Flexibilité : nous accueillons par heure, selon les désirs des parents et non par blocs d’heures obligatoires.</li>
        <li>Pas de caution lors de l’inscription.</li>
        <li>Tout est compris : les langes, lingettes…ne sont pas facturés.</li>
        <li>Seules les présences réelles de l’enfant à la crèche sont facturées : s’il est excusé, ce n’est pas facturé.</li>
        <li>Pour les enfants inscrits auparavant à la crèche entre 0 et 2 ans et qui vont au Précoce, nous continuons à les encadrer en dehors des heures d'école.</li>
        <li>Personnel stable parlant Luxembourgeois, Français, Allemand et Portugais.</li>
        <li>Petite crèche qui privilégie l’ambiance familiale car le nombre de place est restreint.</li>
        <li>Sorties chaque semaine : piscine, airtramp, hall sportif et excursions…</li>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/impressum.html.erb
  <%= render "layouts/banner5_livredor" %>


<div class="card-description">
  <ul class="barre barre-pills barre-justified">
    <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
    <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
    <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
    <li ><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
    <li ><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>
  </ul>
</div>
<div class="card-description">
   <h2><strong><u>Copyright :</u></strong></h2>


              <p> L'ensemble de ce site relève des législations en vigueur sur les droits d'auteur et de la propriété intellectuelle.</p>
              <p>Le contenu de ce site Internet, c.à.d. tous textes, images, photos et autres données sont la propriété de Krabbelstuff asbl et sont protégés par les droits de propriété intellectuelle.</p>
              <p>La reproduction et l’utilisation de tous documents, photos et informations publiés est expressément interdite et sanctionnée pénalement.</p>

</div>

app/views/tasks/index.html.erb
  <%= render "layouts/banner5_livredor" %>


  <div class="card-description">
    <ul class="barre barre-pills barre-justified">
     <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
     <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
     <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
     <li><a href="activités"><%= image_tag("activite.png", alt: 'Activités',) %></a></li>
     <li class='active'><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a></li>
   </ul>
 </div>

  <p class="notice"><%= notice %></p>
<div class="card-description">

  <div class="card-distributed">
      <h2><strong><u>Vos messages</u></strong></h2>
  <div class="card-index">
    <div class="card-index-centered-button">
       <%= link_to "Nouveau message", livredornew_path, class: "button"%>
    </div>
     <div class="card-index-list">
        <%@tasks.each do |task| %>
            <%if task.statut == true %>
          <li>
            <div class="lo-list"><%=task.name%> parent de <%=task.child_name%> année : <%=task.promotion%> </div>
           <p><%=task.description %></p>
            <% end %>
          </li>
          <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/tasks/new.html.erb
  <%= render "layouts/banner5_livredor" %>

  <div class="card-description">
    <ul class="barre barre-pills barre-justified">
     <li><a href="home"><%= image_tag("home.png", alt: 'home',) %></a></li>
     <li><a href="accueil"><%= image_tag("accueil.png", alt: 'accueil',) %></a></li>
     <li><a href="concept"><%= image_tag("concept.png", alt: 'concept.png',) %></a></li>
     <li><a href="activités"><%= image_tag("activités.png", alt: 'Activités',) %></a></li>
     <li class='active'><a href="livredor"><%= image_tag("livredor.png", alt: 'livredor',) %></a>
    </ul>
 </div>
   <div class="card-description">
    <div class="card-distributed">
      <div class="card-ldo first">
        <div class="card-ldo-left">
          <table>
            <tr>
            <%= form_for @task do |f| %>
              <%if @task.errors.any? %>
                <ul class="errors">
                  <%@task.errors.each_with_index do |message, i| %>
                  <li><%=message[1]%> </li>
                  <% end%>
                </ul>
                <% end%>

              <td>Votre prénom: </td>
              <td> <%= f.text_field :name %></td>
            </tr>
            <tr>
              <td>Prénom de l'Enfant: </td>
              <td><%= f.text_field :child_name %></td>
            </tr>
            <tr>
              <td>Année: </td>
              <td><%= f.text_field :promotion %></td>
            </tr>

           </table>
          </div>
          <div class="card-ldo-right">
            <p> Votre message : </p>
            <%= f.text_area :description %>
          </div>
          <div class="card-ldo-down">
              <%= f.submit value="Valider", class: "button" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>